import React, { useState, useEffect } from 'react';

function ReceiptAnalyzer() {
    const [isMobile, setIsMobile] = useState(false);

    useEffect(() => {
        const checkIfMobile = () => {
            setIsMobile(window.innerWidth < 768);
        };

        checkIfMobile();

        window.addEventListener('resize', checkIfMobile);

        return () => window.removeEventListener('resize', checkIfMobile);
    }, []);

    // Assuming your nav bar height is 60px. Adjust as needed.
    const navBarHeight = 60;

    return (
        <main>
            <div
                style={{
                    fontFamily: 'Inter, system-ui, sans-serif',
                    margin: '0',
                    padding: `${40 + navBarHeight}px 20px 40px 20px`, // Added navBarHeight to top padding
                    backgroundColor: '#121212',
                    color: '#f5f5f5',
                    minHeight: '100vh',
                    width: '100%',
                    boxSizing: 'border-box',
                }}
            >
                <div style={{ maxWidth: '1200px', margin: '0 auto' }}>
                    <h1
                        style={{
                            fontSize: 'clamp(2.5rem, 8vw, 3rem)',
                            marginTop: '2rem',
                            marginBottom: '20px',
                            color: 'white',
                            fontWeight: '700',
                            textAlign: isMobile ? 'center' : 'left',
                        }}
                    >
                        AI Receipt Analyzer
                    </h1>

                    <p
                        style={{
                            fontSize: 'clamp(1rem, 4vw, 1.2rem)',
                            marginBottom: '40px',
                            color: '#a0a0a0',
                            maxWidth: '800px',
                            lineHeight: '1.6',
                            textAlign: isMobile ? 'center' : 'left',
                        }}
                    >
                        A full-stack web application that streamlines receipt management and expense tracking through secure cloud storage and automated processing capabilities.
                    </p>

                    {/* Section for Description */}
                    <div
                        style={{
                            display: 'flex',
                            flexDirection: isMobile ? 'column' : 'row',
                            marginBottom: '60px',
                            gap: isMobile ? '15px' : '40px',
                        }}
                    >
                        <div
                            style={{
                                flex: isMobile ? '1' : '0 0 200px',
                            }}
                        >
                            <h2
                                style={{
                                    fontSize: 'clamp(1.4rem, 3vw, 1.8rem)',
                                    color: 'white',
                                    fontWeight: '600',
                                }}
                            >
                                Description
                            </h2>
                        </div>
                        <div
                            style={{
                                flex: '1',
                                backgroundColor: 'rgba(255, 255, 255, 0.05)',
                                padding: 'clamp(15px, 3vw, 30px)',
                                borderRadius: '8px',
                                border: '1px solid rgba(255, 255, 255, 0.1)',
                            }}
                        >
                            <p style={{ lineHeight: '1.8', marginBottom: '20px' }}>
                                The Receipt Analyzer is a modern full-stack web application built with <b>React</b> and <b>TypeScript</b> on the frontend, powered by a <b>Python Flask</b> backend architecture. The application enables users to upload receipt images or PDFs through an intuitive React interface, creating a solid foundation for automated expense tracking and personal finance management.
                                
                                The backend leverages <b>AWS Lambda</b> functions accessed through <b>API Gateway</b> for serverless scalability, with secure file uploads implemented using <b>AWS S3 pre-signed URLs</b> generated by the Flask application. The system utilizes <b>Boto3</b> for seamless AWS service integration, ensuring reliable and secure file storage. The architecture is strategically designed to support future <b>OCR integration</b> for automated receipt data parsing and intelligent spending categorization, establishing a robust foundation for comprehensive personal finance analysis and expense tracking capabilities.
                            </p>
                        </div>
                    </div>

                    {/* Section for Problem */}
                    <div
                        style={{
                            display: 'flex',
                            flexDirection: isMobile ? 'column' : 'row',
                            marginBottom: '60px',
                            gap: isMobile ? '15px' : '40px',
                        }}
                    >
                        <div
                            style={{
                                flex: isMobile ? '1' : '0 0 200px',
                            }}
                        >
                            <h2
                                style={{
                                    fontSize: 'clamp(1.4rem, 3vw, 1.8rem)',
                                    color: 'white',
                                    fontWeight: '600',
                                }}
                            >
                                Problem
                            </h2>
                        </div>
                        <div
                            style={{
                                flex: '1',
                                backgroundColor: 'rgba(255, 255, 255, 0.05)',
                                padding: 'clamp(15px, 3vw, 30px)',
                                borderRadius: '8px',
                                border: '1px solid rgba(255, 255, 255, 0.1)',
                            }}
                        >
                            <p style={{ lineHeight: '1.8', marginBottom: '20px' }}>
                                Managing personal finances and tracking expenses remains a significant challenge for individuals and businesses alike. Traditional expense tracking methods are time-consuming and error-prone, creating barriers to effective financial management:
                            </p>
                            <ul
                                style={{
                                    lineHeight: '1.8',
                                    paddingLeft: '20px',
                                    marginBottom: '20px',
                                }}
                            >
                                <li style={{ marginBottom: '10px' }}>
                                    Manual data entry from receipts is tedious and leads to tracking avoidance
                                </li>
                                <li style={{ marginBottom: '10px' }}>
                                    Physical receipts are easily lost, damaged, or become illegible over time
                                </li>
                                <li style={{ marginBottom: '10px' }}>
                                    Lack of centralized storage makes expense categorization and analysis difficult
                                </li>
                                <li>Inconsistent expense tracking prevents accurate budgeting and financial planning</li>
                            </ul>
                            <p style={{ lineHeight: '1.8' }}>
                                Without proper receipt management and automated processing capabilities, users struggle to maintain accurate financial records, leading to missed tax deductions, poor spending insights, and difficulty in achieving long-term financial goals.
                            </p>
                        </div>
                    </div>

                    {/* Section for Demo with Video */}
                    <div
                        style={{
                            display: 'flex',
                            flexDirection: isMobile ? 'column' : 'row',
                            marginBottom: '60px',
                            gap: isMobile ? '15px' : '40px',
                        }}
                    >
                        <div
                            style={{
                                flex: isMobile ? '1' : '0 0 200px',
                            }}
                        >
                            <h2
                                style={{
                                    fontSize: 'clamp(1.4rem, 3vw, 1.8rem)',
                                    color: 'white',
                                    fontWeight: '600',
                                }}
                            >
                                Demo
                            </h2>
                        </div>
                        <div
                            style={{
                                flex: '1',
                                backgroundColor: 'rgba(255, 255, 255, 0.05)',
                                padding: 'clamp(15px, 3vw, 30px)',
                                borderRadius: '8px',
                                border: '1px solid rgba(255, 255, 255, 0.1)',
                            }}
                        >
                            {/* Video Container */}
                            <div style={{
                                position: 'relative',
                                width: '100%',
                                height: 'clamp(300px, 40vw, 500px)',
                                overflow: 'hidden',
                                borderRadius: '8px',
                                backgroundColor: '#565c63'
                            }}>
                                <video
                                    controls
                                    style={{
                                        width: '100%',
                                        height: '100%',
                                        objectFit: 'contain',
                                        borderRadius: '8px',
                                        backgroundColor: '#000',
                                        filter: 'blur(0px)',
                                        boxShadow: '0 0 20px rgba(255, 255, 255, 0.1)',
                                    }}
                                >
                                    <source src="/ai-receipt-demo.mov" type="video/mp4" />
                                    Your browser does not support the video tag.
                                </video>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    );
}

export default ReceiptAnalyzer;